### ISSUE TITLE
How can I access the kata-gpu-artifacts image

### ISSUE THREAD

**Issue by liricky** [NVIDIA/k8s-kata-manager#1]
In your example, an url "stg.nvcr.io/nvidia/cloud-native/kata-gpu-artifacts:ubuntu22.04-525" is mentioned for pulling the required kata-gpu-artifacts mirror, but the registry-server is not mentioned. 
Is there any more detailed information that would allow me to get this mirror, or are there other alternative mirrors that could be used.
PS: The main reason is that I want to be able to skip the steps of building the kernel and image for kata. This repository seems to simplify the deployment of kata, thx a lot.

**Comment by cdesiniotis** [comment]
Hi @liricky the artifacts are not publicly available yet. We are working to publish them in the coming days.

**Comment by liricky** [comment]
> Hi @liricky the artifacts are not publicly available yet. We are working to publish them in the coming days.
